---

- name: Include server installation tasks
  ansible.builtin.include_tasks:
    file: install-server.yml

- name: Include client installation tasks
  ansible.builtin.include_tasks:
    file: install-client.yml
